DeclareGlobalFunction("BrauerMorphismOfEndRingAsAlgebraHomomorphism");

DeclareGlobalFunction("InvariantBasisAndBrauerQuotientOfTrivialSourceModule");

DeclareSynonym("InvariantBasisAndBrauerQuotient", InvariantBasisAndBrauerQuotientOfTrivialSourceModule);
